export const graphData = {
  nodes: [
    {
      id: "1",
      title: "Golang",
      description: `Golang (Go) is designed for simplicity, high performance, and efficient concurrency. 
              It features fast compilation, a powerful standard library, and lightweight goroutines`,
      size: 6,
      url: "",
      group: 1,
    },
    {
      id: "1.1",
      title: "Golang Runtime",
      description: `A core engine responsible for managing program execution, 
        handling Goroutine scheduling (concurrency), automatic memory management (Garbage Collection), 
        and optimizing resource allocation across multi-core processors.`,
      size: 2,
      url: "https://medium.com/@vungocthuan1234/list/golang-runtime-8ee40ca93176",
      group: 1,
    },
    {
      id: "2",
      title: "SQL",
      description:
        "Standard programming language designed for managing and manipulating data within relational databases",
      size: 6,
      url: "",
      group: 2,
    },
    {
      id: "2.1",
      title: "SQL Query Plan",
      description: `An SQL Query Plan is an execution roadmap generated by the database optimizer 
        to determine the most efficient way to access data, detailing steps like index scans, 
        joins, and filters to minimize resource consumption`,
      size: 2,
      url: "https://medium.com/@vungocthuan1234/sql-explain-command-query-plan-fc90654d5f15",
      group: 2,
    },
    {
      id: "3",
      title: "Linux Fundamentals",
      description: `Introduces the essential concepts of the Linux operating system. 
          Learners will explore core commands, file management, and system administration basics`,
      size: 6,
      url: "https://drive.google.com/drive/folders/11SM_v5r_LB32-qiFGjE6addrHv_xIfLz?usp=sharing",
      group: 3,
    },
  ],
  links: [
    { source: "1", target: "1.1" },
    { source: "2", target: "2.1" },
  ],
};
