"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Briefcase, ChevronDown, ExternalLink } from "lucide-react";

const experiences = [
  {
    id: "exp-1",
    company: "National Digital Twin 15",
    role: "Junior Backend Developer",
    period: "June 2025 – Present",
    description:
      "Recruited via a competitive talent selection program in collaboration with HCMUT-VNU.",
    achievements: [
      "Designed and implemented scalable backend services using Python (FastAPI) and microservices for high-frequency IoT data ingestion.",
      "Optimized complex SQL queries and indexing in PostgreSQL, resulting in a 30% reduction in query latency.",
      "Architected database indexing strategies and implemented PBAC (Policy-Based Access Control) for secure data access.",
      "Integrated Redis caching and background job processing to ensure high availability during peak loads.",
    ],
    skills: ["FastAPI", "PostgreSQL", "Microservices", "Redis", "TypeORM"],
  },
  {
    id: "exp-2",
    company: "HPCC Lab (VNU-HCM)",
    role: "Student Contributor",
    period: "June 2024 – June 2025",
    description:
      "Collaborated with researchers to productionalize automated irrigation systems.",
    achievements: [
      "Developed a robust NestJS backend to execute automated irrigation scripts generated by ML models.",
      "Integrated MLflow to manage model versioning and track experiments, bridging research and production.",
      "Translated complex irrigation algorithms into scalable API services using WebSockets for real-time communication.",
      "Automated deployment lifecycles by architecting CI/CD pipelines with GitHub Actions.",
    ],
    skills: ["NestJS", "MLflow", "WebSockets", "Docker", "GitHub Actions"],
    link: "https://antamtuoi.hpcc.vn",
  },
  {
    id: "exp-3",
    company: "ATOM Solution",
    role: "Fresher Backend Developer",
    period: "Sep 2023 – Dec 2024",
    description:
      "Data-driven platform focused on large-scale data processing and system optimization.",
    achievements: [
      "Developed and deployed Smart Contracts on Ethereum, ensuring high accuracy in automated blockchain transactions.",
      "Customized Odoo modules to automate internal accounting and inventory workflows, improving operational efficiency by 20%.",
    ],
    skills: ["Odoo", "Smart Contract", "Blockchain"],
  },
];

export const WorkExperience = () => {
  const [openIds, setOpenIds] = useState<string[]>(["exp-1"]);

  const toggleAccordion = (id: string) => {
    setOpenIds((prev) =>
      prev.includes(id)
        ? prev.filter((openId) => openId !== id)
        : [...prev, id],
    );
  };

  return (
    <section
      id="experience"
      className="bg-white dark:bg-zinc-950 transition-colors duration-300"
    >
      <div className="mx-auto max-w-7xl px-6">
        {/* Section Header - Matches ProjectsSection.tsx */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="mb-8"
        >
          <h2 className="text-4xl md:text-5xl font-black tracking-tight text-zinc-900 dark:text-zinc-50 mb-4 uppercase">
            Work{" "}
            <span className="text-emerald-500 font-black">Experience.</span>
          </h2>
          <p className="text-sm text-zinc-500 dark:text-zinc-400 font-medium uppercase tracking-[0.2em]">
            Career Path & Professional Impact
          </p>
        </motion.div>

        {/* Scrollable container with utility classes from globals.css */}
        <div className="relative max-h-[800px] overflow-y-auto pr-1 no-scrollbar py-1 border-y border-zinc-100 dark:border-zinc-900/50">
          <div className="relative space-y-12 before:absolute before:inset-0 before:ml-5 before:-translate-x-px md:before:mx-auto md:before:translate-x-0 before:h-full before:w-0.5 before:bg-zinc-100 dark:before:bg-zinc-800/50">
            {experiences.map((exp) => {
              const isOpen = openIds.includes(exp.id);

              return (
                <div
                  key={exp.id}
                  className="relative flex items-start justify-between md:justify-normal md:odd:flex-row-reverse group"
                >
                  {/* Timeline Dot with Emerald Glow */}
                  <div
                    className={`border-3 flex items-center justify-center w-10 h-10 rounded-xl border transition-all duration-500 shrink-0 md:order-1 md:group-odd:-translate-x-1/2 md:group-even:translate-x-1/2 z-10 ${
                      isOpen
                        ? "border-emerald-500 bg-zinc-900 dark:bg-zinc-50 text-emerald-500 shadow-[0_0_20px_rgba(16,185,129,0.3)] rotate-12"
                        : "border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-950 text-zinc-400"
                    }`}
                  >
                    <Briefcase size={16} />
                  </div>

                  {/* Glassmorphism Card */}
                  <div
                    className={`w-[calc(100%-4rem)] md:w-[45%] rounded-[32px] border-2 transition-all duration-500 ${
                      isOpen
                        ? "border-emerald-500/20 bg-zinc-50/50 dark:bg-zinc-900/30 backdrop-blur-md shadow-xl shadow-emerald-500/5"
                        : "border-zinc-100 dark:border-zinc-900 bg-transparent hover:border-emerald-500/10"
                    }`}
                  >
                    {/* Header: Clickable Area */}
                    <button
                      onClick={() => toggleAccordion(exp.id)}
                      className="w-full text-left p-6 md:p-8 flex items-center justify-between gap-4 outline-none group/btn"
                    >
                      <div className="flex-1">
                        <div className="flex items-center gap-3 mb-3">
                          <span className="font-mono text-[10px] text-zinc-400 font-bold tracking-tighter bg-zinc-100 dark:bg-zinc-800/50 px-2 py-0.5 rounded uppercase">
                            {exp.period}
                          </span>
                          {exp.link && (
                            <a
                              href={exp.link}
                              target="_blank"
                              onClick={(e) => e.stopPropagation()}
                              className="text-emerald-500 hover:scale-110 transition-transform"
                            >
                              <ExternalLink size={14} />
                            </a>
                          )}
                        </div>
                        <h4 className="text-xl font-black tracking-tighter text-zinc-900 dark:text-zinc-50 leading-tight mb-1 group-hover/btn:text-emerald-500 transition-colors">
                          {exp.company}
                        </h4>
                        <p className="text-[10px] font-bold text-emerald-500 uppercase tracking-[0.2em]">
                          {exp.role}
                        </p>
                      </div>
                      <motion.div
                        animate={{ rotate: isOpen ? 180 : 0 }}
                        className={`transition-colors p-2 rounded-full ${isOpen ? "bg-emerald-500 text-white" : "bg-zinc-100 dark:bg-zinc-800 text-zinc-400"}`}
                      >
                        <ChevronDown size={18} />
                      </motion.div>
                    </button>

                    {/* Expandable Content */}
                    <AnimatePresence initial={false}>
                      {isOpen && (
                        <motion.div
                          initial={{ height: 0, opacity: 0 }}
                          animate={{ height: "auto", opacity: 1 }}
                          exit={{ height: 0, opacity: 0 }}
                          transition={{
                            duration: 0.4,
                            ease: [0.04, 0.62, 0.23, 0.98],
                          }}
                        >
                          <div className="px-8 pb-8 space-y-6 border-t border-zinc-100 dark:border-zinc-800/50 pt-6">
                            <ul className="space-y-4">
                              {exp.achievements.map((item, i) => (
                                <li
                                  key={i}
                                  className="flex gap-4 text-[13px] text-zinc-600 dark:text-zinc-400 leading-relaxed group/item"
                                >
                                  <div className="mt-1.5 h-1.5 w-1.5 rounded-full bg-emerald-500 shrink-0 group-hover/item:scale-150 transition-transform" />
                                  <span>{item}</span>
                                </li>
                              ))}
                            </ul>

                            {/* Tech Badges - Matches ProjectsSection styles */}
                            <div className="flex flex-wrap gap-2 pt-4">
                              {exp.skills.map((skill) => (
                                <span
                                  key={skill}
                                  className="px-2 py-0.5 bg-zinc-100 dark:bg-zinc-800 text-[9px] font-black text-zinc-500 dark:text-zinc-400 rounded uppercase tracking-tighter"
                                >
                                  {skill}
                                </span>
                              ))}
                            </div>
                          </div>
                        </motion.div>
                      )}
                    </AnimatePresence>
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        {/* Dynamic Footer Indicator */}
        <div className="mt-12 flex flex-col items-center gap-3">
          <div className="h-10 w-px bg-gradient-to-b from-emerald-500 to-transparent animate-pulse" />
          <p className="text-[9px] font-black text-zinc-400 dark:text-zinc-500 uppercase tracking-[0.3em] flex items-center gap-2">
            <span className="w-1 h-1 rounded-full bg-emerald-500 animate-ping" />
            Scroll to explore full history
          </p>
        </div>
      </div>
    </section>
  );
};
