"use client";

import { useState } from "react";
import { Navbar } from "@/components/layout/navbar";
import { motion, AnimatePresence } from "framer-motion";
import {
  FaGithub,
  FaExternalLinkAlt,
  FaYoutube,
  FaDocker,
  FaDollarSign,
  FaRocket,
  FaGlobeAsia,
  FaDatabase,
  FaLeaf,
  FaChevronDown,
} from "react-icons/fa";
import { ArrowLeft, Server, Cpu, Database, Share2 } from "lucide-react";
import Link from "next/link";

const allProjects = [
  {
    year: "2026",
    title: "Gopher Pay",
    tagline: "High-Throughput Payment Engine",
    description:
      "Architected a robust microservices infrastructure designed for high availability and fault tolerance in distributed environments.",
    stack: ["Golang", "Kafka", "Redis", "Postgres", "GORM"],
    challenge:
      "Ensuring zero message loss and consistency while processing over 10,000+ transactions per second.",
    achievements: [
      "Integrated Apache Kafka for seamless asynchronous data flow during peak traffic.",
      "Leveraged service mesh technologies for reliable service integration.",
      "Implemented loosely coupled architecture to allow independent scaling of services.",
    ],
    image: "/assets/projects/GopherPay-Large.jpg",
    links: { github: "https://github.com/thuanvu301103/GopherPay" },
    icon: <FaDollarSign className="text-green-500" />,
    metrics: {
      arch: "Microservices",
      throughput: "10k+ TPS",
      reliability: "99.99%",
    },
  },
  {
    year: "2026",
    title: "PromptLib",
    tagline: "Enterprise AI Prompt Management",
    description:
      "A scalable full-stack architecture ensuring clear separation of concerns for complex AI prompt management.",
    stack: ["NestJS", "NextJS", "MongoDB", "Docker"],
    challenge:
      "Optimizing NoSQL schemas for high-performance metadata filtering and full-text search.",
    achievements: [
      "Designed flexible MongoDB schemas to version and store complex prompt templates.",
      "Containerized all services using Docker to ensure environment consistency.",
      "Streamlined CI/CD pipelines for automated deployment workflows.",
    ],
    image: "/assets/projects/PromptLib Project.gif",
    links: {
      github: "https://github.com/thuanvu301103/PromptLib",
      youtube: "https://youtu.be/NZ8I06xu3vk",
      docker: "https://hub.docker.com/u/thuanvu301103",
    },
    icon: <FaRocket className="text-cyan-500" />,
    metrics: { arch: "Fullstack", db: "NoSQL", devops: "Dockerized" },
  },
  {
    year: "2025",
    title: "National Digital Twin 15",
    tagline: "Large-scale Digital Twin",
    description:
      "Platform designed to comprehensively replicate Vietnam’s entire territorial data for high-frequency ingestion.",
    stack: ["FastAPI", "Clickhouse", "Postgres", "Redis"],
    challenge:
      "Optimizing complex SQL queries and indexing to reduce latency by 30%.",
    achievements: [
      "Designed database indexing strategies and pagination for read-heavy API performance.",
      "Implemented Redis caching to significantly reduce database load.",
      "Orchestrated automated migrations using TypeORM to ensure 100% data integrity.",
    ],
    image: "/assets/projects/National Digital Twin 15 Project.jpg",
    links: {
      link: "https://ctgroupvietnam.com/national-digital-twin-15-ndt-15/",
    },
    icon: <FaGlobeAsia className="text-blue-400" />,
    metrics: { latency: "-30%", arch: "Microservices", db: "PostgreSQL" },
  },
  {
    year: "2025",
    title: "Smart Farming Portal",
    tagline: "IoT & ML Automation Platform",
    description:
      "A robust backend system to manage and execute automated irrigation scripts generated by Machine Learning models.",
    stack: ["NestJS", "PostgreSQL", "MLflow", "IoT", "WebSockets"],
    challenge:
      "Translating complex irrigation algorithms into scalable API services while handling massive sensor datasets.",
    achievements: [
      "Integrated MLflow to manage model versioning and track experiments for production-ready ML.",
      "Collaborated with researchers to implement real-time IoT sensor data processing.",
      "Automated irrigation workflows ensuring seamless transition from research to production.",
    ],
    image: "/assets/projects/SmartFarming-Large.jpg",
    links: {
      github: "https://github.com/thuanvu301103/Smart-Farming-Web-portal",
      link: "https://antamtuoi.hpcc.vn",
    },
    icon: <FaLeaf className="text-pink-500" />,
    metrics: { integration: "MLflow", realTime: "WebSockets", data: "IoT Hub" },
  },
  {
    year: "2024",
    title: "Bank Statement Search",
    tagline: "High-Performance Indexing",
    description:
      "High-performance backend built to process and index large-scale financial datasets for rapid retrieval.",
    stack: ["NestJS", "Docker", "Postgres", "Algorithms"],
    challenge:
      "Reducing search response time by 60% compared to standard linear queries.",
    achievements: [
      "Designed custom Search Algorithms for optimized data filtering and lookups.",
      "Automated the build and deployment lifecycle via GitHub Actions.",
      "Architected CI/CD pipelines ensuring seamless delivery to Docker Hub.",
    ],
    image: "/assets/projects/BankSearch.jpg",
    links: {
      github: "https://github.com/thuanvu301103/Bank-statement-Search-website",
      docker:
        "https://hub.docker.com/repository/docker/thuanvu301103/bank-statement-app",
    },
    icon: <FaDatabase className="text-purple-500" />,
    metrics: { speed: "+60%", devops: "GitHub Actions", arch: "Monolith" },
  },
];

export default function ProjectsArchive() {
  const [expandedIndex, setExpandedIndex] = useState<number | null>(null);

  return (
    <div className="min-h-screen bg-white dark:bg-[#0a0a0a] text-zinc-900 dark:text-zinc-100 selection:bg-emerald-500/30">
      <Navbar />

      <main className="mx-auto max-w-7xl px-6 pt-32 pb-20">
        <Link
          href="/"
          className="group mb-8 inline-flex items-center gap-2 text-[10px] font-black uppercase tracking-[0.2em] text-emerald-500 transition-colors"
        >
          <ArrowLeft
            size={14}
            className="transition-transform group-hover:-translate-x-1"
          />
          Return to Dashboard
        </Link>

        <header className="mb-16">
          <h1 className="text-6xl md:text-8xl font-black tracking-tighter mb-4">
            ENGINEERING.
            <br />
            <span className="text-emerald-500">LOGS.</span>
          </h1>
          <p className="text-zinc-500 font-medium uppercase text-[11px] tracking-[0.3em] max-w-xl leading-relaxed">
            A specialized collection of backend systems, microservices
            architectures, and high-performance data pipelines.
          </p>
        </header>

        <div className="space-y-4">
          {allProjects.map((project, i) => (
            <div
              key={project.title}
              className="group rounded-3xl border border-zinc-200 dark:border-zinc-800 bg-zinc-50/50 dark:bg-zinc-900/20 overflow-hidden transition-all hover:border-emerald-500/30"
            >
              {/* Table Row Header */}
              <div
                onClick={() => setExpandedIndex(expandedIndex === i ? null : i)}
                className="flex flex-wrap items-center justify-between p-6 md:p-8 cursor-pointer"
              >
                <div className="flex items-center gap-6 flex-1 min-w-[300px]">
                  <span className="font-mono text-xs text-zinc-400">
                    {project.year}
                  </span>
                  <div className="text-2xl">{project.icon}</div>
                  <div className="flex flex-col">
                    <h3 className="text-xl font-extrabold tracking-tight">
                      {project.title}
                    </h3>
                    <span className="text-[10px] font-bold text-emerald-500 uppercase tracking-widest">
                      {project.tagline}
                    </span>
                  </div>
                </div>

                <div className="hidden lg:flex items-center gap-3 px-8 border-x border-zinc-200 dark:border-zinc-800 mx-8">
                  {project.stack.slice(0, 3).map((s) => (
                    <span
                      key={s}
                      className="text-[9px] font-bold px-2 py-1 bg-zinc-100 dark:bg-zinc-800 rounded uppercase text-zinc-500"
                    >
                      {s}
                    </span>
                  ))}
                </div>

                <div className="flex items-center gap-6">
                  <div className="flex gap-4">
                    {project.links.github && (
                      <a
                        href={project.links.github}
                        target="_blank"
                        className="text-zinc-400 hover:text-zinc-900 dark:hover:text-white transition-colors"
                      >
                        <FaGithub size={18} />
                      </a>
                    )}
                    {project.links.docker && (
                      <a
                        href={project.links.docker}
                        target="_blank"
                        className="text-zinc-400 hover:text-blue-500 transition-colors"
                      >
                        <FaDocker size={18} />
                      </a>
                    )}
                    {project.links.youtube && (
                      <a
                        href={project.links.youtube}
                        target="_blank"
                        className="text-zinc-400 hover:text-red-500 transition-colors"
                      >
                        <FaYoutube size={18} />
                      </a>
                    )}
                    {project.links.link && (
                      <a
                        href={project.links.link}
                        target="_blank"
                        className="text-zinc-400 hover:text-emerald-500 transition-colors"
                      >
                        <FaExternalLinkAlt size={16} />
                      </a>
                    )}
                  </div>
                  <motion.div
                    animate={{ rotate: expandedIndex === i ? 180 : 0 }}
                  >
                    <FaChevronDown className="text-zinc-300" />
                  </motion.div>
                </div>
              </div>

              {/* Expandable Content */}
              <AnimatePresence>
                {expandedIndex === i && (
                  <motion.div
                    initial={{ height: 0, opacity: 0 }}
                    animate={{ height: "auto", opacity: 1 }}
                    exit={{ height: 0, opacity: 0 }}
                    className="border-t border-zinc-100 dark:border-zinc-800/50"
                  >
                    <div className="p-8 grid grid-cols-1 lg:grid-cols-2 gap-12">
                      {/* Left side: Large Image & Metrics */}
                      <div className="space-y-6">
                        <div className="aspect-video rounded-2xl overflow-hidden bg-zinc-100 dark:bg-zinc-800 border border-zinc-200 dark:border-zinc-700">
                          <img
                            src={project.image}
                            className="w-full h-full object-cover"
                          />
                        </div>
                      </div>

                      {/* Right side: Detailed CV Info */}
                      <div className="space-y-8">
                        <div>
                          <h4 className="text-[10px] font-black uppercase tracking-[0.2em] text-emerald-500 mb-3">
                            Project Overview
                          </h4>
                          <p className="text-sm text-zinc-600 dark:text-zinc-400 leading-relaxed">
                            {project.description}
                          </p>
                        </div>
                        <div>
                          <h4 className="text-[10px] font-black uppercase tracking-[0.2em] text-emerald-500 mb-3">
                            Key Technical Challenges
                          </h4>
                          <div className="p-4 rounded-xl bg-red-500/5 border border-red-500/10">
                            <p className="text-xs text-zinc-500 dark:text-zinc-400 italic">
                              "{project.challenge}"
                            </p>
                          </div>
                        </div>
                        <div>
                          <h4 className="text-[10px] font-black uppercase tracking-[0.2em] text-emerald-500 mb-3">
                            Selected Achievements
                          </h4>
                          <ul className="space-y-3">
                            {project.achievements.map((item, idx) => (
                              <li
                                key={idx}
                                className="flex gap-3 text-xs text-zinc-600 dark:text-zinc-300"
                              >
                                <span className="h-1.5 w-1.5 rounded-full bg-emerald-500 mt-1.5 shrink-0" />
                                {item}
                              </li>
                            ))}
                          </ul>
                        </div>
                      </div>
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>
            </div>
          ))}
        </div>
      </main>
    </div>
  );
}
